create table if not exists public.votos (
  id bigint generated by default as identity primary key,
  numero integer,
  nome text not null default '',
  chapa text not null default '',
  cor text not null default '',
  tipo text not null check (tipo in ('válido', 'branco', 'nulo')),
  data_hora timestamptz not null default now()
);

alter table public.votos enable row level security;

create policy "Permitir registro de votos"
on public.votos
for insert
to anon
with check (true);
