export type GeneroGrupo = 'menino' | 'menina';
export type GrupoDiscipulado = { id: string; nome: string; genero: GeneroGrupo; formacoes: string[] };

export const gruposDiscipulado: GrupoDiscipulado[] = [
  { id: 'alaor', nome: 'Alaor', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'felipe-garcia', nome: 'Dc. Felipe Garcia', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'willian', nome: 'Dc. Willian', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'g-ferreira', nome: 'G. Ferreira', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'jander', nome: 'Jander', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'm-melo', nome: 'M. Melo', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'samuel-jesus', nome: 'Samuel de Jesus', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'tarik', nome: 'Tarik', genero: 'menino', formacoes: ['Pr. Rafa e Dc. Pedro'] },
  { id: 'pedro-gustavo', nome: 'Dc. Pedro + Gustavo', genero: 'menino', formacoes: ['Dc. Junio e Dc. Matheus', 'Pr. Rafa e Dc. Pedro'] },
  { id: 'william-andre', nome: 'William + André', genero: 'menino', formacoes: ['Dc. Felipe e Dc. Willian'] },
  { id: 'felipe-jose-flavio', nome: 'Felipe + José Flávio', genero: 'menino', formacoes: ['Dc. Felipe e Dc. Willian'] },
  { id: 'danth-carlos', nome: 'Danthe + Carlos', genero: 'menino', formacoes: ['Dc. Junio e Dc. Matheus'] },
  { id: 'matheus-g-palacio', nome: 'Matheus + G. Palácio', genero: 'menino', formacoes: ['Dc. Junio e Dc. Matheus'] },
  { id: 'ester-tamires', nome: 'Ester Rodrigues + Tamires', genero: 'menina', formacoes: ['Dc. Ester'] },
  { id: 'fernanda-manu', nome: 'Fernanda + Manu', genero: 'menina', formacoes: ['A. Borges e M. Laura'] },
  { id: 'emily-m-eugenia', nome: 'Mª Eugênia + Emily', genero: 'menina', formacoes: ['A. Borges e M. Laura'] },
  { id: 'sabrina-sophia', nome: 'Sabrina + Sophia Motta', genero: 'menina', formacoes: ['Dc. Carole e Dc. Sabrina'] },
  { id: 'amanda-brenda', nome: 'Amanda Gonçalo + Brenda', genero: 'menina', formacoes: ['A. Borges e M. Laura', 'Dc. Ester'] },
  { id: 'bianca-debora', nome: 'Bianca + Débora', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta', 'Dc. Carole e Dc. Sabrina'] },
  { id: 'lia-taisa', nome: 'Lia + Taísa', genero: 'menina', formacoes: ['Dc. Carole e Dc. Sabrina'] },
  { id: 'thais-gaminha', nome: 'Thaís + Gaminha', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
  { id: 'jessica-paula', nome: 'Jéssica + Paula', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
  { id: 'vitoria-lorrana', nome: 'Vitória Ferreira + Lorrana', genero: 'menina', formacoes: ['Dc. Carole e Dc. Sabrina'] },
  { id: 'gama-sara', nome: 'Gama + Sara Franco', genero: 'menina', formacoes: ['A. Borges e M. Laura'] },
  { id: 'anna-ester', nome: 'Anna Lia + Ester Machado', genero: 'menina', formacoes: ['Dc. Ester'] },
  { id: 'roberta-diuliana', nome: 'Roberta + Diuliana', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
  { id: 'phublyane-anna', nome: 'Phublyane + Anna Gabriella', genero: 'menina', formacoes: ['A. Borges e M. Laura'] },
  { id: 'ana-clara-vitoria', nome: 'Ana Clara + V. Lima', genero: 'menina', formacoes: ['Dc. Carole e Dc. Sabrina'] },
  { id: 'yasmin-luana', nome: 'Yasmin Bastos + Luana', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
  { id: 'isadora-mag', nome: 'Isadora + L. Magalhães', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
  { id: 'maria-laura-elisa', nome: 'Maria Laura + Elisa', genero: 'menina', formacoes: ['A. Borges e M. Laura', 'Dc. Ester'] },
  { id: 'thalyta', nome: 'Thályta', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
  { id: 'y-moraes-beatriz', nome: 'Y. Moraes + Beatriz', genero: 'menina', formacoes: ['Dc. Y. Moraes e Dc. Thalyta'] },
];
